In [1]:
from io import StringIO
from scipy.io import mmread
from scipy.io import mminfo
from google.colab import drive
drive.mount("/content/drive")
datAddr = "/content/drive/MyDrive/"
from scipy.sparse import csr_matrix
from scipy import sparse
import numpy as np

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
m = mmread(datAddr+'tumorAntiAngiogenesis_6.mtx')
m_csr = m.tocsr()

In [ ]:
def write_in_chunks(f, lst, n):
    for i in range(0, len(lst), n):
        chunk = lst[i : i+n]
        f.write(" ".join(str(val) for val in chunk) + "\n")

In [ ]:
with open(datAddr+'output3.txt', "w") as f:
    write_in_chunks(f, m_csr.indices, 8)

## Creating a small example to test on

In [15]:
row_mat = 4
cols_mat= 4

mat1 = [[0 for _ in range(cols_mat)] for _ in range(row_mat)]
# editing the individual elements
mat1[0][0], mat1[0][1], mat1[0][2], mat1[0][3] = 0,0,8,0
mat1[1][0], mat1[1][1], mat1[1][2], mat1[1][3] = 7,9,6,0
mat1[2][0], mat1[2][1], mat1[2][2], mat1[2][3] = 0,5,0,4
mat1[3][0], mat1[3][1], mat1[3][2], mat1[3][3] = 3,0,0,2
print(f'Matrix is {mat1}')
mat_csr = sparse.csr_matrix(mat1)

Matrix is [[0, 0, 8, 0], [7, 9, 6, 0], [0, 5, 0, 4], [3, 0, 0, 2]]


## Baseline Architecture 
 

In [63]:
def PE_mult(PE_lst_index, output_row_num, output_col_num):
  # ToDO: whichever the vector is or the row has fewer non-zeroes that list we iterate over that first 
  accumulation = 0
  for col,data in B_dict.items():
    if col in PE_lst[PE_lst_index]:
      # multiply and then accumulate  
      accumulation += PE_lst[PE_lst_index][col] * data  
  output_mat2[output_row_num][output_col_num] = accumulation 
      



In [65]:
PE_mult(0, 0, 0)
PE_mult(1, 0, 1)
PE_mult(2, 0, 2)
PE_mult(3, 0, 3)

In [66]:
output_mat2

[[0, 7, 16, 11], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [53]:
PE_lst = []
output_mat2 = [[0 for _ in range(cols_mat)] for _ in range(row_mat)]
data_index = 0
col_index = 0
pointer_index = 0

# assigning the vector that will stay in PE
dataB_row = [1, 4]
colB_row = [0, 3]
B_dict = dict(zip(colB_row, dataB_row))

for i in range(4):
  numOfElems = (mat_csr.indptr[pointer_index + 1] - mat_csr.indptr[pointer_index])
  data_row = mat_csr.data[data_index:numOfElems+data_index]
  col_row = mat_csr.indices[col_index:numOfElems+data_index]
  print(data_row)
  print(col_row)
  PE_lst.append(dict(zip(col_row, data_row)))
  data_index += numOfElems
  col_index += numOfElems
  pointer_index += 1

print(PE_lst)


[8]
[2]
[7 9 6]
[0 1 2]
[5 4]
[1 3]
[3 2]
[0 3]
[{2: 8}, {0: 7, 1: 9, 2: 6}, {1: 5, 3: 4}, {0: 3, 3: 2}]


In [10]:
mat_csr.data[0:1]

array([8])